### ISSUE TITLE
xmind-org-root-node: Wrong type argument: hash-table-p, nil

### ISSUE THREAD

**Issue by emacle** [akirak/xmind-org-el#4]
xmind-org-root-node: Wrong type argument: hash-table-p, nil

GNU Emacs 28.1 (build 1, x86_64-apple-darwin20.6.0, Carbon Version 164 AppKit 2022.6) of 2022-05-04 
  xmind-org 20201202.1605

**Comment by akirak** [comment]
Thanks for reporting this issue. I think I have fixed the bug. If the issue is still remaining on your machine, please feel free to reopen this ticket.
